### ISSUE TITLE
Banner image hidden too much by header

### ISSUE THREAD

**Issue by Keale2** [unumux/landing-page-vdm-cl#1]
The header is covering important parts of the banner image. Consider adding extra junk to the top of the banner image in Photoshop.

**Comment by Keale2** [comment]
Person should be visible and centered vertically in banner.

**Comment by ArcaneMainFrame** [comment]
Second comment is about desktop size for reference.

**Comment by ArcaneMainFrame** [comment]
Was able to achieve with background-position.
